"""empty message

Revision ID: dd672e540bb3
Revises: 
Create Date: 2020-05-21 18:19:51.789962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd672e540bb3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'articles', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'user_id')
    # ### end Alembic commands ###
